function [ output_args ] = drawConstantWindow( input_args )
%UNTITLED Summary of this function goes here
%   Detailed explanation goes here

global binaryD data g pltVr datVr prgVr wndVr datWndVr datWndLabVr;
%% Draw Window
binaryD = 1;
if ishandle(g)
    close(g)
end
g = figure;
if size(wndVr.monPos,1) > 1
    set(g,'Position',wndVr.monPos(size(wndVr.monPos,1)-1,:));
end
drawnow;
pause(0.1);
jFrame = get(handle(g),'JavaFrame');
jFrame.setMaximized(true);
pause(0.1);
P2 = get(g,'pos');
%set(g,'DefaultFigurePosition', P2,'DefaultAxesPosition', [0.4,0.1,0.5,0.7]);
set(g,'pos', P2,'DefaultAxesPosition', [0.4,0.1,0.5,0.7]);
colors      =   linspecer(8);
set(g,'BackingStore','off','MenuBar','figure','NumberTitle','off','Name','Calibration Constants & Other Functions','Color','g');
set(g,'DefaultUicontrolUnits','normalized','DefaultUicontrolFontUnits','normalized',...
    'DefaultUicontrolFontSize',0.45,'DefaultUicontrolFontWeight','bold')
ax = gca;
set(ax,'handlevisibility','off','visible','off');
% This creates the 'background' axes
ha = axes('units','normalized', ...
    'position',[0 0 1 1]);
% Move the background axes to the bottom
uistack(ha,'bottom');
% Load in a background image and display it using the correct colors
% The image used below, is in the Image Processing Toolbox.  If you do not have %access to this toolbox, you can use another image file instead.
I=imread('BackgroundImage.jpg');
hi = imagesc(I);
colormap gray;
% Turn the handlevisibility off so that we don't inadvertently plot into the axes again
% Also, make the axes invisible
set(ha,'handlevisibility','off', ...
    'visible','off');
exportplot = -1;

%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
% Positions of text boxes in the main window

edge        =   0.01;
wid1        =   (0.6)*((1-9*edge)/4);
wid2        =   (0.6)*((1-9*edge)/4);
left1       =   2*edge;
left2       =   3*edge+wid1;
left3       =   6*edge+wid1+wid2;
left4       =   7*edge+2*wid1+wid2;
left5       =   10*edge+3*wid1+wid2;
left6       =   11*edge+4*wid1+wid2;
titlefs     =   0.5;
bot_title   =   0.835;

for i = 1 : 14, eval(['bot' num2str(i) '= bot_title - (i-1) * 0.06;']); end;
for i = 1 : 16, eval(['bbot' num2str(i) '= bot_title + 0.02 - (i-1) * 0.065;']); end;
height      =   0.045;
color       =   [0.7 0.7 0.7];
color1      =   colors(2,:);%[0.6 0.8 0.9];
color2      =   'w';
color3      =   colors(5,:);%[0.6550 0.75 0.4722];
color_x     =   [0.6 0.1 0.8];
color_y     =   [0.2 0.7 0.3];
%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
%% Physical Constants
set(0,'Currentfigure',g)
datWndLabVr.physCst  = uicontrol('Style','text', ...
    'Position',[left1 bbot1+1.25*height 2*(wid1)+edge height], ...
    'String','Physical Constants',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.physCst);
%%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
% datWndLabVr.dualCst.kB  = uicontrol('Style','pushbutton', ...
%     'Position',[left1 bbot6+1.25*height 1*(wid1)+0.5*edge height], ...
%     'String','<html><b>1<sub>2</sub>3<sup>4</sup>5</b></html>',...
%     'BackgroundColor',color1,...
%     'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndLabVr.dualCst.kB  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot2+1.5*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Boltzmann (m<sup>2</sup> kg s<sup>-2</sup> K<sup>-1</sup>)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndVr.dualCst.kB = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot2+1.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.kB),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.kB,''String''))) == 1) && ~isempty(data) datVr.dualCst.kB = min(max(str2num([get(datWndVr.dualCst.kB,''String'')]),0),100000); set(datWndVr.dualCst.kB,''String'', num2str(datVr.dualCst.kB)); datVr.dualCst.eta = (datVr.dualCst.viscC(1) +  datVr.dualCst.viscC(2)*exp(datVr.dualCst.alphaC(1).*datVr.dualCst.TC) + datVr.dualCst.viscC(3)*exp(datVr.dualCst.alphaC(2).*datVr.dualCst.m) + datVr.dualCst.viscC(4)*exp(datVr.dualCst.alphaC(3).*(0.01.*datVr.dualCst.TC + datVr.dualCst.m)) + datVr.dualCst.viscC(5)*exp(datVr.dualCst.alphaC(4).*(0.01.*datVr.dualCst.TC - datVr.dualCst.m)))*1E-3; set(datWndVr.dualCst.eta,''String'', num2str(datVr.dualCst.eta)); datVr.dualCst.gam1 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam1*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam1; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); if(prgVr.setupStt == 2) datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); datVr.dualCst.gam4 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam4*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam4; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end; end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.T  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot3+1.75*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Temperature (K)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndVr.dualCst.T = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot3+1.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.T),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.T,''String''))) == 1) && ~isempty(data) datVr.dualCst.T = min(max(str2num([get(datWndVr.dualCst.T,''String'')]),0),100000); datVr.dualCst.TC = datVr.dualCst.T-273.15; set(datWndVr.dualCst.T,''String'', num2str(datVr.dualCst.T)); datVr.dualCst.eta = (datVr.dualCst.viscC(1) +  datVr.dualCst.viscC(2)*exp(datVr.dualCst.alphaC(1).*datVr.dualCst.TC) + datVr.dualCst.viscC(3)*exp(datVr.dualCst.alphaC(2).*datVr.dualCst.m) + datVr.dualCst.viscC(4)*exp(datVr.dualCst.alphaC(3).*(0.01.*datVr.dualCst.TC + datVr.dualCst.m)) + datVr.dualCst.viscC(5)*exp(datVr.dualCst.alphaC(4).*(0.01.*datVr.dualCst.TC - datVr.dualCst.m)))*1E-3; set(datWndVr.dualCst.eta,''String'', num2str(datVr.dualCst.eta)); datVr.dualCst.gam1 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam1*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam1; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2));  if(prgVr.setupStt == 2) datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); datVr.dualCst.gam4 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam4*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam4; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end; end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.m  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot3+0.5*height 1*(wid1)+0.5*edge height], ...
    'String','<html>+1 Ion Concentration (M)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndVr.dualCst.m = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot3+0.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.m),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.m,''String''))) == 1) && ~isempty(data) datVr.dualCst.m = min(max(str2num([get(datWndVr.dualCst.m,''String'')]),0),100000); datVr.dualCst.eta = (datVr.dualCst.viscC(1) +  datVr.dualCst.viscC(2)*exp(datVr.dualCst.alphaC(1).*datVr.dualCst.TC) + datVr.dualCst.viscC(3)*exp(datVr.dualCst.alphaC(2).*datVr.dualCst.m) + datVr.dualCst.viscC(4)*exp(datVr.dualCst.alphaC(3).*(0.01.*datVr.dualCst.TC + datVr.dualCst.m)) + datVr.dualCst.viscC(5)*exp(datVr.dualCst.alphaC(4).*(0.01.*datVr.dualCst.TC - datVr.dualCst.m)))*1E-3; set(datWndVr.dualCst.m,''String'', num2str(datVr.dualCst.m)); set(datWndVr.dualCst.eta,''String'', num2str(datVr.dualCst.eta)); datVr.dualCst.gam1 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam1*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam1; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); if(prgVr.setupStt == 2) datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); datVr.dualCst.gam4 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam4*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam4; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); datVr.pDNA = max(calcPDNA( (datVr.dualCst.m+datVr.dualCst.m2), (1*datVr.dualCst.m+2*datVr.dualCst.m2)/(datVr.dualCst.m+datVr.dualCst.m2) ),1); set(datWndVr.pDNA,''String'', num2str(datVr.pDNA)); end; end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.m2  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot4+0.75*height 1*(wid1)+0.5*edge height], ...
    'String','<html>+2 Ion Concentration (M)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndVr.dualCst.m2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot4+0.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.m2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.m2,''String''))) == 1) && ~isempty(data) datVr.dualCst.m2 = min(max(str2num([get(datWndVr.dualCst.m2,''String'')]),0),100000); datVr.pDNA = max(calcPDNA( (datVr.dualCst.m+datVr.dualCst.m2), (1*datVr.dualCst.m+2*datVr.dualCst.m2)/(datVr.dualCst.m+datVr.dualCst.m2) ),1); set(datWndVr.pDNA,''String'', num2str(datVr.pDNA)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.eta  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot5+1.0*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Viscosity (Pa s)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
set(0,'Currentfigure',g)
datWndVr.dualCst.eta = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot5+1.0*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.eta),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.eta,''String''))) == 1) && ~isempty(data) datVr.dualCst.eta = min(max(str2num([get(datWndVr.dualCst.eta,''String'')]),0),100000); set(datWndVr.dualCst.eta,''String'', num2str(datVr.dualCst.eta)); datVr.dualCst.gam1 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam1*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam1; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); if(prgVr.setupStt == 2) datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); datVr.dualCst.gam4 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam4*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam4; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end; end;');
%% WLC Constants
set(0,'Currentfigure',g)
datWndLabVr.wlcCst = uicontrol('Style','text', ...
    'Position',[left1 bbot7+1.25*height 2*(wid1)+edge height], ...
    'String','WLC Constants',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.wlcCst);
%%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.basepairs  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot7 1*(wid1)+0.5*edge height], ...
    'String','DNA Base Pairs (#)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.basepairs);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.basepairs = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot7 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.basepairs),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.basepairs,''String''))) == 1) && ~isempty(data) datVr.basepairs = min(max(str2num([get(datWndVr.basepairs,''String'')]),0),100000); set(datWndVr.basepairs,''String'', num2str(datVr.basepairs)); end;');
set(0,'Currentfigure',g)
datWndLabVr.baseL  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot8+0.25*height 1*(wid1)+0.5*edge height], ...
    'String','Base Pair length (nm)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.baseL);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.baseL = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot8+0.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.baseL),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.baseL,''String''))) == 1) && ~isempty(data) datVr.baseL = min(max(str2num([get(datWndVr.baseL,''String'')]),0),100000); set(datWndVr.baseL,''String'', num2str(datVr.baseL)); end;');
set(0,'Currentfigure',g)
datWndLabVr.pDNA  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot9+0.5*height 1*(wid1)+0.5*edge height], ...
    'String','DNA Persistence L (nm)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.pDNA);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.pDNA = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot9+0.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.pDNA),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.pDNA,''String''))) == 1) && ~isempty(data) datVr.pDNA = min(max(str2num([get(datWndVr.pDNA,''String'')]),1),100000); set(datWndVr.pDNA,''String'', num2str(datVr.pDNA)); end;');
set(0,'Currentfigure',g)
datWndLabVr.KDNA  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot10+0.75*height 1*(wid1)+0.5*edge height], ...
    'String','DNA Stretch M (Pa)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.KDNA);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.KDNA = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot10+0.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.KDNA*1E9),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.KDNA,''String''))) == 1) && ~isempty(data) datVr.KDNA = min(max(str2num([get(datWndVr.KDNA,''String'')]),1),100000)*1E-9; set(datWndVr.KDNA,''String'', num2str(datVr.KDNA*1E9)); end;');
jh = findjobj(datWndLabVr.KDNA);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.residues  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot11+1*height 1*(wid1)+0.5*edge height], ...
    'String','Protein Residues (#)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.residues);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.residues = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot11+1*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.residues),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.residues,''String''))) >= 1) && ~isempty(data) datVr.residues = min(max(str2num([get(datWndVr.residues,''String'')]),0),100000); datVr.residues = sort(datVr.residues); set(datWndVr.residues,''String'', num2str(datVr.residues)); end;');
set(0,'Currentfigure',g)
datWndLabVr.resL  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot12+1.25*height 1*(wid1)+0.5*edge height], ...
    'String','Residue Length (nm)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.resL);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.resL = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot12+1.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.resL),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.resL,''String''))) == 1) && ~isempty(data) datVr.resL = min(max(str2num([get(datWndVr.resL,''String'')]),0),100000); set(datWndVr.resL,''String'', num2str(datVr.resL)); end;');
jh = findjobj(datWndLabVr.resL);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.pPROT  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot13+1.5*height 1*(wid1)+0.5*edge height], ...
    'String','Protein Persistence L (nm)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.pPROT);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.pPROT = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot13+1.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.pPROT*1E9),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.pPROT,''String''))) == 1) && ~isempty(data) datVr.pPROT = min(max(str2num([get(datWndVr.pPROT,''String'')]),1),100000)*1E-9; set(datWndVr.pPROT,''String'', num2str(datVr.pPROT*1E9)); end;');
jh = findjobj(datWndLabVr.pPROT);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.KPROT  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot14+1.75*height 1*(wid1)+0.5*edge height], ...
    'String','Protein Stretch M (Pa)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.KPROT);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.KPROT = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot14+1.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.KPROT*1E9),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.KPROT,''String''))) == 1) && ~isempty(data) datVr.KPROT = min(max(str2num([get(datWndVr.KPROT,''String'')]),1),100000)*1E-9; set(datWndVr.KPROT,''String'', num2str(datVr.KPROT*1E9)); end;');
jh = findjobj(datWndLabVr.KDNA);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.rulB  = uicontrol('Style','pushbutton', ...
    'Position',[left1 bbot15+2*height 2*(wid1)+1*edge height], ...
    'String','Create Ruler',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','createRuler(''test'', datVr.dualCst.T, datVr.dualCst.kB, datVr.basepairs, datVr.baseL, datVr.pDNA, datVr.KDNA, datVr.residues, datVr.resL, datVr.pPROT,  datVr.KPROT)');
jh = findjobj(datWndLabVr.rulB);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
%% Trap 1 - X Constants
set(0,'Currentfigure',g)
datWndLabVr.trap1Cst  = uicontrol('Style','text', ...
    'Position',[left3 bbot1+1.25*height 2*(wid1)+edge height], ...
    'String','Trap 1 - X Constants',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.trap1Cst);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.dualCst.Dex1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot1 1*(wid1)+0.5*edge height], ...
    'String','Experimental D (A.U.)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.Dex1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.Dex1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot1 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.Dex1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.Dex1,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dex1 = min(max(str2num([get(datWndVr.dualCst.Dex1,''String'')]),0.0001),100000000); set(datWndVr.dualCst.Dex1,''String'', num2str(datVr.dualCst.Dex1)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.cFreq1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot2+0.25*height 1*(wid1)+0.5*edge height], ...
    'String','Corner Frequency (Hz)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.cFreq1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.cFreq1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot2+0.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.cFreq1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.cFreq1,''String''))) == 1) && ~isempty(data) datVr.dualCst.cFreq1 = min(max(str2num([get(datWndVr.dualCst.cFreq1,''String'')]),0),100000000); set(datWndVr.dualCst.cFreq1,''String'', num2str(datVr.dualCst.cFreq1)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.R1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot3+0.5*height 1*(wid1)+0.5*edge height], ...
    'String','Bead Radius (m)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.R1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.R1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot3+0.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.R1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.R1,''String''))) == 1) && ~isempty(data) datVr.dualCst.R1 = min(max(str2num([get(datWndVr.dualCst.R1,''String'')]),0),100000000); set(datWndVr.dualCst.R1,''String'', num2str(datVr.dualCst.R1)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R1; datVr.dualCst.k1 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq1*10^6; set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); datVr.dualCst.Dth1 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.k1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot4+0.75*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Trap Stiffness (pN/&#x3BC;m)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.k1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.k1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot4+0.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.k1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.k1,''String''))) == 1) && ~isempty(data) datVr.dualCst.k1 = min(max(str2num([get(datWndVr.dualCst.k1,''String'')]),0),100000000); set(datWndVr.dualCst.k1,''String'', num2str(datVr.dualCst.k1)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.Dth1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot5+1*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Theoretical Diff. (m<sup>2</sup>/s)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.Dth1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.Dth1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot5+1*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.Dth1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.Dth1,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dth1 = min(max(str2num([get(datWndVr.dualCst.Dth1,''String'')]),0),100000000); set(datWndVr.dualCst.Dth1,''String'', num2str(datVr.dualCst.Dth1)); datVr.dualCst.alpha1 = sqrt(datVr.dualCst.Dth1/datVr.dualCst.Dex1)*10^6; set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.alpha1  = uicontrol('Style','pushbutton', ...
    'Position',[left3 bbot6+1.25*height 1*(wid1)+0.5*edge height], ...
    'String','<html>&#x3B1; (&#x3BC;m/A.U.)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.alpha1);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.alpha1 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left4-0.5*edge bbot6+1.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.alpha1),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.alpha1,''String''))) == 1) && ~isempty(data) datVr.dualCst.alpha1 = min(max(str2num([get(datWndVr.dualCst.alpha1,''String'')]),0),100000000); set(datWndVr.dualCst.alpha1,''String'', num2str(datVr.dualCst.alpha1)); end;');
%% Trap 2 - X Constants
set(0,'Currentfigure',g)
datWndLabVr.trap2Cst  = uicontrol('Style','text', ...
    'Position',[left5 bbot1+1.25*height 2*(wid1)+edge height], ...
    'String','Trap 2 - X Constants',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.trap2Cst);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndLabVr.dualCst.Dex2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot1 1*(wid1)+0.5*edge height], ...
    'String','Experimental D (A.U.)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.Dex2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.Dex2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot1 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.Dex2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.Dex2,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dex2 = min(max(str2num([get(datWndVr.dualCst.Dex2,''String'')]),0.0001),100000000); set(datWndVr.dualCst.Dex2,''String'', num2str(datVr.dualCst.Dex2)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.cFreq2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot2+0.25*height 1*(wid1)+0.5*edge height], ...
    'String','Corner Frequency (Hz)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.cFreq2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.cFreq2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot2+0.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.cFreq2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.cFreq2,''String''))) == 1) && ~isempty(data) datVr.dualCst.cFreq2 = min(max(str2num([get(datWndVr.dualCst.cFreq2,''String'')]),0),100000000); set(datWndVr.dualCst.cFreq2,''String'', num2str(datVr.dualCst.cFreq2)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.R2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot3+0.5*height 1*(wid1)+0.5*edge height], ...
    'String','Bead Radius (m)',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.R2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.R2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot3+0.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.R2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.R2,''String''))) == 1) && ~isempty(data) datVr.dualCst.R2 = min(max(str2num([get(datWndVr.dualCst.R2,''String'')]),0),100000000); set(datWndVr.dualCst.R2,''String'', num2str(datVr.dualCst.R2)); datVr.dualCst.gam2 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R2; datVr.dualCst.k2 = 2*pi*datVr.dualCst.gam2*datVr.dualCst.cFreq2*10^6; set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); datVr.dualCst.Dth2 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam2; set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth2/datVr.dualCst.Dex2)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.k2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot4+0.75*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Trap Stiffness (pN/&#x3BC;m)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.k2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.k2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot4+0.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.k2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.k2,''String''))) == 1) && ~isempty(data) datVr.dualCst.k2 = min(max(str2num([get(datWndVr.dualCst.k2,''String'')]),0),100000000); set(datWndVr.dualCst.k2,''String'', num2str(datVr.dualCst.k2)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.Dth2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot5+1*height 1*(wid1)+0.5*edge height], ...
    'String','<html>Theoretical Diff. (m<sup>2</sup>/s)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.Dth2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.Dth2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot5+1*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.Dth2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.Dth2,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dth2 = min(max(str2num([get(datWndVr.dualCst.Dth2,''String'')]),0),100000000); set(datWndVr.dualCst.Dth2,''String'', num2str(datVr.dualCst.Dth2)); datVr.dualCst.alpha2 = sqrt(datVr.dualCst.Dth21/datVr.dualCst.Dex21)*10^6; set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); end;');
set(0,'Currentfigure',g)
datWndLabVr.dualCst.alpha2  = uicontrol('Style','pushbutton', ...
    'Position',[left5 bbot6+1.25*height 1*(wid1)+0.5*edge height], ...
    'String','<html>&#x3B1; (&#x3BC;m/A.U.)</html>',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(datWndLabVr.dualCst.alpha2);
%jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',g)
datWndVr.dualCst.alpha2 = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left6-0.5*edge bbot6+1.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.dualCst.alpha2),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(datWndVr.dualCst.alpha2,''String''))) == 1) && ~isempty(data) datVr.dualCst.alpha2 = min(max(str2num([get(datWndVr.dualCst.alpha2,''String'')]),0),100000000); set(datWndVr.dualCst.alpha2,''String'', num2str(datVr.dualCst.alpha2)); end;');
%% Trap 1 - Y Constants

if(prgVr.setupStt == 1 || prgVr.setupStt == 2)
    set(0,'Currentfigure',g)
    datWndLabVr.trap3Cst  = uicontrol('Style','text', ...
        'Position',[left3 bbot7+1.25*height 2*(wid1)+edge height], ...
        'String','Trap 1 - Y Constants',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.trap3Cst);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.Dex3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot7 1*(wid1)+0.5*edge height], ...
        'String','Experimental D (A.U.)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.Dex3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.Dex3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot7 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.Dex3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.Dex3,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dex3 = min(max(str2num([get(datWndVr.dualCst.Dex3,''String'')]),0.0001),100000000); set(datWndVr.dualCst.Dex3,''String'', num2str(datVr.dualCst.Dex3)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.cFreq3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot8+0.25*height 1*(wid1)+0.5*edge height], ...
        'String','Corner Frequency (Hz)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.cFreq3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.cFreq3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot8+0.25*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.cFreq3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.cFreq3,''String''))) == 1) && ~isempty(data) datVr.dualCst.cFreq3 = min(max(str2num([get(datWndVr.dualCst.cFreq3,''String'')]),0),100000000); set(datWndVr.dualCst.cFreq3,''String'', num2str(datVr.dualCst.cFreq3)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.R3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot9+0.5*height 1*(wid1)+0.5*edge height], ...
        'String','Bead Radius (m)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.R3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.R3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot9+0.5*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.R3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.R3,''String''))) == 1) && ~isempty(data) datVr.dualCst.R3 = min(max(str2num([get(datWndVr.dualCst.R3,''String'')]),0),100000000); set(datWndVr.dualCst.R3,''String'', num2str(datVr.dualCst.R3)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R3; datVr.dualCst.k3 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq3*10^6; set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); datVr.dualCst.Dth3 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.k3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot10+0.75*height 1*(wid1)+0.5*edge height], ...
        'String','<html>Trap Stiffness (pN/&#x3BC;m)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.k3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.k3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot10+0.75*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.k3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.k3,''String''))) == 1) && ~isempty(data) datVr.dualCst.k3 = min(max(str2num([get(datWndVr.dualCst.k3,''String'')]),0),100000000); set(datWndVr.dualCst.k3,''String'', num2str(datVr.dualCst.k3)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.Dth3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot11+1*height 1*(wid1)+0.5*edge height], ...
        'String','<html>Theoretical Diff. (m<sup>2</sup>/s)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.Dth3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.Dth3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot11+1*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.Dth3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.Dth3,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dth3 = min(max(str2num([get(datWndVr.dualCst.Dth3,''String'')]),0),100000000); set(datWndVr.dualCst.Dth3,''String'', num2str(datVr.dualCst.Dth3)); datVr.dualCst.alpha3 = sqrt(datVr.dualCst.Dth3/datVr.dualCst.Dex3)*10^6; set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.alpha3  = uicontrol('Style','pushbutton', ...
        'Position',[left3 bbot12+1.25*height 1*(wid1)+0.5*edge height], ...
        'String','<html>&#x3B1; (&#x3BC;m/A.U.)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.alpha3);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.alpha3 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left4-0.5*edge bbot12+1.25*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.alpha3),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.alpha3,''String''))) == 1) && ~isempty(data) datVr.dualCst.alpha3 = min(max(str2num([get(datWndVr.dualCst.alpha3,''String'')]),0),100000000); set(datWndVr.dualCst.alpha3,''String'', num2str(datVr.dualCst.alpha3)); end;');
    
end
%% Trap 2 - Y Constants

if(prgVr.setupStt == 1 || prgVr.setupStt == 2)
    
    set(0,'Currentfigure',g)
    datWndLabVr.trap4Cst  = uicontrol('Style','text', ...
        'Position',[left5 bbot7+1.25*height 2*(wid1)+edge height], ...
        'String','Trap 2 - Y Constants',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.trap4Cst);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.Dex4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot7 1*(wid1)+0.5*edge height], ...
        'String','Experimental D (A.U.)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.Dex4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.Dex4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot7 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.Dex4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.Dex4,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dex4 = min(max(str2num([get(datWndVr.dualCst.Dex4,''String'')]),0.0001),100000000); set(datWndVr.dualCst.Dex4,''String'', num2str(datVr.dualCst.Dex4)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.cFreq4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot8+0.25*height 1*(wid1)+0.5*edge height], ...
        'String','Corner Frequency (Hz)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.cFreq4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.cFreq4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot8+0.25*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.cFreq4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.cFreq4,''String''))) == 1) && ~isempty(data) datVr.dualCst.cFreq4 = min(max(str2num([get(datWndVr.dualCst.cFreq4,''String'')]),0),100000000); set(datWndVr.dualCst.cFreq4,''String'', num2str(datVr.dualCst.cFreq4)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.R4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot9+0.5*height 1*(wid1)+0.5*edge height], ...
        'String','Bead Radius (m)',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.R4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.R4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot9+0.5*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.R4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.R4,''String''))) == 1) && ~isempty(data) datVr.dualCst.R4 = min(max(str2num([get(datWndVr.dualCst.R4,''String'')]),0),100000000); set(datWndVr.dualCst.R4,''String'', num2str(datVr.dualCst.R4)); datVr.dualCst.gam3 = 6*pi*datVr.dualCst.eta*datVr.dualCst.R4; datVr.dualCst.k4 = 2*pi*datVr.dualCst.gam3*datVr.dualCst.cFreq4*10^6; set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); datVr.dualCst.Dth4 = datVr.dualCst.kB*datVr.dualCst.T/datVr.dualCst.gam3; set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.k4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot10+0.75*height 1*(wid1)+0.5*edge height], ...
        'String','<html>Trap Stiffness (pN/&#x3BC;m)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.k4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.k4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot10+0.75*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.k4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.k4,''String''))) == 1) && ~isempty(data) datVr.dualCst.k4 = min(max(str2num([get(datWndVr.dualCst.k4,''String'')]),0),100000000); set(datWndVr.dualCst.k4,''String'', num2str(datVr.dualCst.k4)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.Dth4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot11+1*height 1*(wid1)+0.5*edge height], ...
        'String','<html>Theoretical Diff. (m<sup>2</sup>/s)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.Dth4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.Dth4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot11+1*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.Dth4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.Dth4,''String''))) == 1) && ~isempty(data) datVr.dualCst.Dth4 = min(max(str2num([get(datWndVr.dualCst.Dth4,''String'')]),0),100000000); set(datWndVr.dualCst.Dth4,''String'', num2str(datVr.dualCst.Dth4)); datVr.dualCst.alpha4 = sqrt(datVr.dualCst.Dth4/datVr.dualCst.Dex4)*10^6; set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end;');
    set(0,'Currentfigure',g)
    datWndLabVr.dualCst.alpha4  = uicontrol('Style','pushbutton', ...
        'Position',[left5 bbot12+1.25*height 1*(wid1)+0.5*edge height], ...
        'String','<html>&#x3B1; (&#x3BC;m/A.U.)</html>',...
        'BackgroundColor',color1,...
        'ForegroundColor',color3);
    jh = findjobj(datWndLabVr.dualCst.alpha4);
    %jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    set(0,'Currentfigure',g)
    datWndVr.dualCst.alpha4 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left6-0.5*edge bbot12+1.25*height 1*(wid2)+0.5*edge height], ...
        'String',num2str(datVr.dualCst.alpha4),...
        'BackgroundColor',color2,...
        'Callback','if(length(str2num(get(datWndVr.dualCst.alpha4,''String''))) == 1) && ~isempty(data) datVr.dualCst.alpha4 = min(max(str2num([get(datWndVr.dualCst.alpha4,''String'')]),0),100000000); set(datWndVr.dualCst.alpha4,''String'', num2str(datVr.dualCst.alpha4)); end;');
    
end
end