function [ ] = drawFoldometerWindow( ) %#ok<STOUT,INUSD>
%UNTITLED3 Summary of this function goes here
%   Detailed explanation goes here
global binaryD data f pltVr datVr prgVr wndVr; %#ok<NUSED>

binaryD = 1;
if ishandle(f)
    close(f)    
end
f = figure;
drawnow;
pause(0.1);
jFrame = get(handle(f),'JavaFrame');
jFrame.setMaximized(true);
pause(0.1);
P2 = get(f,'pos');
%set(f,'DefaultFigurePosition', P2,'DefaultAxesPosition', [0.4,0.1,0.5,0.7]);
set(f,'pos', P2,'DefaultAxesPosition', [0.4,0.1,0.5,0.7]);
colors      =   linspecer(8);
set(f,'BackingStore','off','MenuBar','figure','NumberTitle','off','Name',['Foldometer Analysis Software ' datVr.ver],'Color','g');
set(f,'DefaultUicontrolUnits','normalized','DefaultUicontrolFontUnits','normalized',...
    'DefaultUicontrolFontSize',0.45,'DefaultUicontrolFontWeight','bold')
set(0,'Currentfigure',f)
ax = gca;
set(ax,'handlevisibility','off','visible','off');
% This creates the 'background' axes
ha = axes('units','normalized', ...
            'position',[0 0 1 1]);
% Move the background axes to the bottom
uistack(ha,'bottom');
% Load in a background image and display it using the correct colors
% The image used below, is in the Image Processing Toolbox.  If you do not have %access to this toolbox, you can use another image file instead.
I=imread('BackgroundImageFoldometer.jpg');
hi = imagesc(I);
colormap gray;
% Turn the handlevisibility off so that we don't inadvertently plot into the axes again
% Also, make the axes invisible
set(ha,'handlevisibility','off', ...
            'visible','off');
exportplot = -1;
%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
% Positions of text boxes in the main window

edge        =   0.01;
wid1        =   (0.6)*((1-9*edge)/4); 
wid2        =   (0.6)*((1-9*edge)/4); 
left1       =   2*edge;
left2       =   3*edge+wid1;
left3       =   6*edge+wid1+wid2;
left4       =   7*edge+2*wid1+wid2;
titlefs     =   0.5;
bot_title   =   0.835;

for i = 1 : 14, eval(['bot' num2str(i) '= bot_title - (i-1) * 0.06;']); end;
for i = 1 : 16, eval(['bbot' num2str(i) '= bot_title + 0.02 - (i-1) * 0.065;']); end;
height      =   0.045;
color       =   [0.7 0.7 0.7];
color1      =   colors(2,:);%[0.6 0.8 0.9];
color2      =   'w';
color3      =   colors(5,:);%[0.6550 0.75 0.4722];
color_x     =   [0.6 0.1 0.8];
color_y     =   [0.2 0.7 0.3];
%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
% Title and the LOAD_TIME_SERIES button

set(0,'Currentfigure',f)
wndVr.hpc  = uicontrol('Style','text','Position',[0.2 0.92 0.6 height+0.01],'String',['Foldometer Analysis Software ' datVr.ver],...
    'FontSize',titlefs+0.2,'ForegroundColor',color3,'BackgroundColor',color1);

set(0,'Currentfigure',f)
wndVr.botPanel = uipanel('BorderType','etchedin',...
		'BackgroundColor',colors(8,:),...
		'Position',[0.325,0.05-edge*3,0.65,0.85+edge*3],...
		'Parent',f);
    figBord = [0.1 0.1 0.8 0.8];
    wndVr.a = axes('parent',wndVr.botPanel,'Position', figBord, 'FontSize', 16);
    
wndVr.axesPos = get(wndVr.botPanel,'pos');

set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 0.9025 0.5*(wid1+wid2)+edge height], ...
    'String','Custom Cal.',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','start_fit;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 0.95 0.5*(wid1+wid2)+edge height], ...
    'String','Quick Cal.',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','extractDataQ;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[1-0.5*(wid1+wid2)-edge*4 0.92 0.5*(wid1+wid2)+edge height], ...
    'String','Ctrap',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','prgVr.setupStt = 2; save([pwd filesep ''progState.mat''],''prgVr'',''-append''); drawCTrapWindow;');
set(0,'Currentfigure',f)
wndVr.legendBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-0.5*(wid1+wid2)-edge*4 bbot1 0.5*(wid1+wid2)+edge height], ...
    'String','Legend ON',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','pltVr.legOn = abs(pltVr.legOn-1); if pltVr.legOn == 0; set(wndVr.legendBut,''String'',''Legend OFF''); else set(wndVr.legendBut,''String'',''Legend ON''); end;');
set(0,'Currentfigure',f)
wndVr.resetAxBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-1*(wid1+wid2)-edge*6 bbot1 0.5*(wid1+wid2)+edge height], ...
    'String','Reset Axis',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data); pltVr.rstAx = 1;  if pltVr.grphAct == 1; data = plotFT(); elseif pltVr.grphAct == 2; data = plotTE(); elseif pltVr.grphAct == 3; data = plotFECombined(); elseif pltVr.grphAct == 4; data = plotSDual(); end; set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); end;');
set(0,'Currentfigure',f)
wndVr.unfBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-1.5*(wid1+wid2)-edge*8 bbot1 0.5*(wid1+wid2)+edge height], ...
    'String','Unf. Event OFF',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','pltVr.unfDet = abs(pltVr.unfDet-1); if pltVr.unfDet == 0; set(wndVr.unfBut,''String'',''Unf. Event OFF''); else set(wndVr.unfBut,''String'',''Unf. Event ON''); end;');
set(0,'Currentfigure',f)
wndVr.WLCBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-2*(wid1+wid2)-edge*10 bbot1 0.5*(wid1+wid2)+edge height], ...
    'String','WLC Fit OFF',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','pltVr.WLCfit = abs(pltVr.WLCfit-1); if pltVr.WLCfit == 0; set(wndVr.WLCBut,''String'',''WLC Fit OFF''); else set(wndVr.WLCBut,''String'',''WLC Fit ON''); end;');
set(0,'Currentfigure',f)
wndVr.biasCalcBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-0.15*(wid1+wid2)-edge*4 bbot3+4*edge 0.15*(wid1+wid2)+edge height], ...
    'String','Calc Bias',...
    'FontSize',(titlefs+0.2)/2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data)&&pltVr.grphAct==3 [datVr.xBias] = []; [datVr.yBias] = []; data = plotFECombined(); [datVr.xBias, datVr.yBias] = getpts(gcf); data = plotFECombined(); end;');
set(0,'Currentfigure',f)
wndVr.contourPlotBut = uicontrol('Style','Pushbutton', ...
    'Position',[1-0.15*(wid1+wid2)-edge*4 bbot4+4*edge 0.15*(wid1+wid2)+edge height], ...
    'String','Plot Lp OFF',...
    'FontSize',(titlefs+0.2)/2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','pltVr.LpPlot = abs(pltVr.LpPlot-1); if pltVr.LpPlot == 0; set(wndVr.contourPlotBut,''String'',''Plot Lp OFF''); else set(wndVr.contourPlotBut,''String'',''Plot Lp ON''); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot1 1*(wid1+wid2)+edge height], ...
    'String','Load Raw Data (*.dat)',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','data = getRaw(); if(~isstruct(data)) data = []; else pltVr.rstAx = 1; pltVr.ftAx = []; pltVr.teAx = []; pltVr.feAx = [0.5 1.5 -10  85]; pltVr.ssAx = []; data = plotFECombined(); data = plotFT(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); wndVr.hTrig = 0; wndVr.vTrig = 0; end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot2+edge 1*(wid1+wid2)+edge height], ...
    'String','Load Processed Data (*.mat)',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','getProc(); set(wndVr.sampling_shift,''String'',num2str([data.shiftX data.shiftY])); set(wndVr.sampling_xlim,''String'',num2str(pltVr.feAx(1:2))); set(wndVr.sampling_ylim,''String'',num2str(pltVr.feAx(3:4))); shiftXTemp = data.shiftX; shiftYTemp = data.shiftY; data = plotFECombined(); set(wndVr.hSlider,''Value'',shiftXTemp); set(wndVr.vSlider,''Value'',shiftYTemp); data.shiftX = shiftXTemp; data.shiftY = shiftYTemp; clear shiftXTemp shiftYTemp; data = plotFECombined();'); %eval(get(wndVr.hSlider, ''Callback'')); eval(get(wndVr.vSlider, ''Callback''));
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot3+2*edge 1*(wid1+wid2)+edge height], ...
    'String','Save Raw Data',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) saveData(); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot4+3*edge 1*(wid1+wid2)+edge height], ...
    'String','Force vs. Time',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) data = plotFECombined(); data = plotFT(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot5+4*edge 1*(wid1+wid2)+edge height], ...
    'String','Time vs. Extension',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) data = plotFECombined(); data = plotTE(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot6+5*edge 1*(wid1+wid2)+edge height], ...
    'String','Force vs. Extension',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) data = plotFECombined(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot7+6*edge 1*(wid1+wid2)+edge height], ...
    'String','Sensitivity',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) data = plotSDual(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot7 1*(wid1)+0.5*edge height], ...
    'String','Select Intervals',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data)&&pltVr.grphAct==1 [data.x, data.y] = getpts(gcf); [data.x, I] = sort(data.x); data.y = data.y(I); data.x = data.x(1:end-mod(length(data.x),2)); data.y = data.y(1:end-mod(length(data.x),2)); clear I; wndVr.hTrig = 0; wndVr.vTrig = 0; end; if(isfield(data, ''scombined'')) data = rmfield(data, {''scombined'', ''force''}); data = plotFECombined(); pltVr.rstAx = 1; data = plotFT(); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left2-0.5*edge bbot7 1*(wid2)+0.5*edge height], ...
    'String','Clear Intervals',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if(isfield(data, ''x'')) data = rmfield(data, {''x'', ''y''}); end; if(isfield(data, ''scombined'')) data = rmfield(data, {''scombined'', ''force''}); wndVr.hTrig = 0; wndVr.vTrig = 0; data = plotFECombined(); pltVr.rstAx = 1; data = plotFT(); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left2-0.5*edge bbot8 1*(wid2)+0.5*edge height], ...
    'String','Plot Separate',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if(isfield(data, ''x'')) plotSeparate(); end;');
set(0,'Currentfigure',f)
uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot8 1*(wid1)+0.5*edge height], ...
    'String','Plot All',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if(isfield(data, ''force'')) plotAll( ); end;');
set(0,'Currentfigure',f)
wndVr.forBut = uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot9 1*(wid1)+0.5*edge height], ...
    'String','Flinear',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) if(prgVr.forStt == 1) set(wndVr.forBut,''String'',''Flinear''); prgVr.forStt = 2; else prgVr.forStt = 1; set(wndVr.forBut,''String'',''Fsmooth''); end; data = plotFECombined(); end;');
set(0,'Currentfigure',f)
wndVr.sampling_const = uicontrol('Style','Pushbutton', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot9 1*(wid2)+0.5*edge height], ...
    'String','Constants',...   
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) drawConstantWindow; end');
set(0,'Currentfigure',f)
wndVr.sensBut = uicontrol('Style','Pushbutton', ...
    'Position',[left1 bbot10 1*(wid1)+0.5*edge height], ...
    'String','Sensitivity Fit',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','if ~isempty(data) if(length(pltVr.fitVal) == 2) pltVr.fitVal = data.dvdx; set(wndVr.sensBut,''String'',''Sensitivity Value''); set(wndVr.sampling_sens,''Enable'',''on'',''String'',num2str(data.dvdx)); else pltVr.fitVal = [0 1]; set(wndVr.sensBut,''String'',''Sensitivity Fit''); set(wndVr.sampling_sens,''String'',num2str(pltVr.fitVal)); end; data = plotFECombined(); end;');
set(0,'Currentfigure',f)
wndVr.sampling_sens = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot10 1*(wid2)+0.5*edge height], ...
    'String',num2str(pltVr.fitVal),...
    'BackgroundColor',color2,...
    'Callback','if length(str2num(get(wndVr.sampling_sens,''String''))) == 1 && ~isempty(data) pltVr.fitVal = max(1,str2num(get(wndVr.sampling_sens,''String''))); data.dvdx = max(1,str2num(get(wndVr.sampling_sens,''String''))); data = plotFECombined(); elseif(length(str2num(get(wndVr.sampling_sens,''String''))) == 2 && exist(''data'') && strcmp(get(wndVr.sensBut,''String''),''Sensitivity Fit'')) pltVr.fitVal = str2num(get(wndVr.sampling_sens,''String'')); pltVr.fitVal(1) = min(max(0, min(pltVr.fitVal(1),pltVr.fitVal(2))),1); pltVr.fitVal(2) = min(max(0, max(pltVr.fitVal(1),pltVr.fitVal(2))),1); if(pltVr.fitVal(2) == 0) pltVr.fitVal(2) = 1; end; set(wndVr.sampling_sens,''String'',num2str(pltVr.fitVal)); data = plotSDual(); end;');


set(0,'Currentfigure',f)
wndVr.hruler  = uicontrol('Style','popup', ...
    'Position',[left1 bbot11+0.25*height 1*(wid1)+0.5*edge height], ...
    'String',' No Ruler | WLC Ruler | MBP Rulers | 4 MBP Rulers | Luciferase Rulers | MBP Rulers dual | alpha-Synuclein Rulers | NCS-1 Rulers | NCS-1 MF Rulers | GR shortlong | Rhodanese | 4Syn | MBP 5.2 kBp handles', ...
    'Callback','pltVr.rulVal = get(wndVr.hruler, ''Value''); if ~isempty(data) data = plotFECombined(); end;', ...
    'BackgroundColor',color1,'ForegroundColor',color3,'Value',2);

set(0,'Currentfigure',f)
wndVr.hsignal  = uicontrol('Style','Pushbutton', ...
    'Position',[left2-0.5*edge bbot11+0.25*height 1*(wid1)+0.5*edge height], ...
    'String','Load Ruler', ...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',color1,...
    'ForegroundColor',color3,...
    'Callback','');

set(0,'Currentfigure',f)
wndVr.hSlider = uicontrol('Style','slider','Position',[0.335,0.05-edge*3,0.64,0.01+edge*(0.65/(0.85+edge*3))],'callback','if ~isempty(data) if(wndVr.hTrig == 0) wndVr.hTrig = 1; data = plotFECombined(); maxTemp = max(cellfun(@(x)max(x(:)), data.scombined)); minTemp = min(cellfun(@(x)min(x(:)), data.scombined)); set(wndVr.hSlider, ''Min'', min(1*(0-maxTemp), 1*(0-minTemp)), ''Max'', max(1*(0-minTemp)+0.9, 1*(0-maxTemp)+0.9), ''Value'', mean([min(1*(0-maxTemp)+0.9, 1*(0-minTemp)+0.9) max(1*(0-minTemp)+0.9, 1*(0-maxTemp)+0.9)]), ''SliderStep'', abs([1 1].*((1*(0-maxTemp))-(1*(0-minTemp)))./1000)); end; data.shiftX = get(wndVr.hSlider,''Value''); set(wndVr.sampling_shift,''String'', num2str([data.shiftX data.shiftY])); data = plotFECombined(); end;');%,'Callback', @(s,e) disp(get(s,'Value')));%'Min',-3,'Max',3,...

set(0,'Currentfigure',f)
wndVr.vSlider = uicontrol('Style','slider','Position',[0.325,0.05-edge*3,0.01,0.85+edge*3],'callback','if ~isempty(data) if(wndVr.vTrig == 0) wndVr.vTrig = 1; data = plotFECombined(); maxTemp = max(cellfun(@(x)max(x(:)), data.force)); minTemp = min(cellfun(@(x)min(x(:)), data.force)); set(wndVr.vSlider, ''Min'', min(1*(0-maxTemp)-0.9, 1*(0-minTemp)-0.9), ''Max'', max(1*(0-minTemp)+0.9, 1*(0-maxTemp)+0.9), ''Value'', max([min(1*(0-maxTemp), 1*(0-minTemp)) max(1*(0-minTemp), 1*(0-maxTemp))]), ''SliderStep'', abs([1 1].*((1*(0-maxTemp))-(1*(0-minTemp)))./1000)); end; data.shiftY = get(wndVr.vSlider,''Value''); set(wndVr.sampling_shift,''String'', num2str([data.shiftX data.shiftY]));  data = plotFECombined(); end;');

set(0,'Currentfigure',f)
wndVr.pt  = uicontrol('Style','text', ...
    'Position',[left1 bbot11-0.75*height 1*(wid1)+0.5*edge height], ...
    'String','Smoothing Parameter',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(wndVr.pt);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );

set(0,'Currentfigure',f)
wndVr.sampling_pol = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot11-0.75*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(datVr.fitPar),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(wndVr.sampling_pol,''String''))) == 1) && ~isempty(data) datVr.fitPar = min(max(str2num([get(wndVr.sampling_pol,''String'')]),0.01),0.9999999); set(wndVr.sampling_pol,''String'', num2str(datVr.fitPar)); data = plotFECombined(); end;');
set(0,'Currentfigure',f)
wndVr.ht  = uicontrol('Style','text', ...
    'Position',[left1 bbot12-0.5*height 1*(wid1)+0.5*edge height], ...
    'String','X bounds',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(wndVr.ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',f)
wndVr.sampling_xlim = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot12-0.5*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(get(gca,'xlim')),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(wndVr.sampling_xlim,''String''))) == 2) && ~isempty(data) xlim([str2num(get(wndVr.sampling_xlim,''String''))]); if pltVr.grphAct==1 pltVr.ftAx(1:2) = str2num(get(wndVr.sampling_xlim,''String'')); elseif pltVr.grphAct==2 pltVr.teAx(3:4) = str2num(get(wndVr.sampling_xlim,''String'')); elseif pltVr.grphAct==3 pltVr.feAx(1:2) = str2num(get(wndVr.sampling_xlim,''String''));  elseif pltVr.grphAct==4 pltVr.ssAx(1:2) = str2num(get(wndVr.sampling_xlim,''String'')); end; end;');
set(0,'Currentfigure',f)
wndVr.vt  = uicontrol('Style','text', ...
    'Position',[left1 bbot13-0.25*height 1*(wid1)+0.5*edge height], ...
    'String','Y bounds',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(wndVr.vt);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',f)
wndVr.sampling_ylim = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot13-0.25*height 1*(wid2)+0.5*edge height], ...
    'String',num2str(get(gca,'ylim')),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(wndVr.sampling_ylim,''String''))) == 2) && ~isempty(data) ylim([str2num(get(wndVr.sampling_ylim,''String''))]); if pltVr.grphAct==1 pltVr.ftAx(3:4) = str2num(get(wndVr.sampling_ylim,''String'')); elseif pltVr.grphAct==2 pltVr.teAx(1:2) = str2num(get(wndVr.sampling_ylim,''String'')); elseif pltVr.grphAct==3 pltVr.feAx(3:4) = str2num(get(wndVr.sampling_ylim,''String'')); elseif pltVr.grphAct==4 pltVr.ssAx(3:4) = str2num(get(wndVr.sampling_ylim,''String'')); end; end;');
set(0,'Currentfigure',f)
wndVr.st  = uicontrol('Style','text', ...
    'Position',[left1 bbot14 1*(wid1)+0.5*edge height], ...
    'String','Shift X-Y',...
    'BackgroundColor',color1,...
    'ForegroundColor',color3);
jh = findjobj(wndVr.st);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
set(0,'Currentfigure',f)
wndVr.sampling_shift = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2-0.5*edge bbot14 1*(wid2)+0.5*edge height], ...
    'String',num2str([0 0]),...
    'BackgroundColor',color2,...
    'Callback','if(length(str2num(get(wndVr.sampling_shift,''String''))) == 2) && ~isempty(data) temp = [str2num(get(wndVr.sampling_shift,''String''))]; data.shiftX = temp(1); data.shiftY = temp(2); data = plotFECombined(); set(wndVr.sampling_xlim,''String'',num2str(get(gca,''xlim''))); set(wndVr.sampling_ylim,''String'',num2str(get(gca,''ylim''))); clear temp; end;');
end