% INPUT_PARA1_DEC makes buttons to see Pxy/sqrt(Px Py) and reads WANT_DECORR 
% (choice of using decorrelation of channels).
want_decorr =   0;              % want_decorr = 1 for decorrelation; otherwise 0 

if (channel(1) ~= 0 && channel(2) ~= 0) || (channel(3) ~= 0 && channel(4) ~= 0)
    hcheckdec = uicontrol('Style','Pushbutton', ...
    'Position',[left1+wid1/2 bbot5 (wid1+wid2)/2 0.9*height], ...
    'String','Check for cross-talk',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',[1 0.1 0.1],...
    'Callback','check_decorr');

hdecorr  = uicontrol('Style','popup', ...
    'Position',[left1 bbot6 wid2+left2-left1 height], ...
    'String',' Do not eliminate cross-talk | Eliminate cross-talk ', ...
    'Callback','decorr_decision', ...
    'BackgroundColor',color1);
else
    hcheckdec  = uicontrol('Style','text','Position',[left1+wid1/2 bbot5 (wid1+wid2)/2 0.9*height],'String',...
        ' ','BackgroundColor',color);
    hdecorr  = uicontrol('Style','text','Position',[left1 bbot6 wid2+left2-left1 height],'String',...
        ' ','BackgroundColor',color);
end;

