% INPUT_PARA3_HYDRO reads  
% R (radius of the bead), L (distance to surface), NU (kinematic
% viscosity), RHOL and RHO (density of the liquid and bead) if choice of inclusion of hydrodynamic correction is chosen. 

%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

R           =   0.5e-6;         % radius of the bead (m)
l           =   5e-6;           % distance to surface (m)
nu          =   1e-12/1e-6;     % kinematic viscosity (m2/s)
rho         =   1e-3/1e-6;      % density of the bead (kg/m3)
rhol        =   1e-3/1e-6;      % density of the liquid (kg/m3)

if want_hydro == 1,
ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot2 wid1 height], ...
    'String',['Radius of the bead (' char(181) 'm)'],...
    'BackgroundColor',color1);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hR = uicontrol('Style','edit', ...
    'Position',[left4 bbot2 wid2 height], ...
    'String',num2str(R*1e6),...
    'BackgroundColor',color2,...
    'Callback','R = 1e-6*str2num(get(hR,''String''));');

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot3 wid1 height], ...
    'String',['Distance to surface (' char(181) 'm)'],...
    'BackgroundColor',color1);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hl = uicontrol('Style','edit', ...
    'Position',[left4 bbot3 wid2 height], ...
    'String',num2str(l*1e6),...
    'BackgroundColor',color2,...
    'Callback','l = 1e-6*str2num(get(hl,''String''));');

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot4 wid1 height], ...
    'String',['Density of bead (g/cm' char(hex2dec('B3')) ')'],...
    'BackgroundColor',color1);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hrho = uicontrol('Style','edit', ...
    'Position',[left4 bbot4 wid2 height], ...
    'String',num2str(rho*1e-3),...
    'BackgroundColor',color2,...
    'Callback','rho = 1e3*str2num(get(hrho,''String''));');

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot5 wid1 height], ...
    'String',['Density of fluid (g/cm' char(hex2dec('B3')) ')'],...
    'BackgroundColor',color1);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hrhol = uicontrol('Style','edit', ...
    'Position',[left4 bbot5 wid2 height], ...
    'String',num2str(rhol*1e-3),...
    'BackgroundColor',color2,...
    'Callback','rhol = 1e3*str2num(get(hrhol,''String''));');

str1(1)={['Kinematic viscosity  ' char(215) ' 1e6 ' char(181) 'm' char(hex2dec('B2')) '/s']};
str1(2)={'Has value 1 for water'};
ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot6 wid1 height], ...
    'String',str1,...
    'BackgroundColor',color1,'fontsize',.4);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hnu = uicontrol('Style','edit', ...
    'Position',[left4 bbot6 wid2 height], ...
    'String',num2str(nu*1e6),...
    'BackgroundColor',color2,...
    'Callback','nu = 1e-6*str2num(get(hnu,''String''));');
else,
ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot2 wid1 height], ...
    'String',' ',...
    'BackgroundColor',color);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hR = uicontrol('Style','text', ...
    'Position',[left4 bbot2 wid2 height], ...
    'String',' ',...
    'BackgroundColor',color);

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot3 wid1 height], ...
    'String',' ',...
    'BackgroundColor',color);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hl = uicontrol('Style','text', ...
    'Position',[left4 bbot3 wid2 height], ...
    'String',' ',...
    'BackgroundColor',color);

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot4 wid1 height], ...
    'String',' ',...
    'BackgroundColor',color);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hrho = uicontrol('Style','text', ...
    'Position',[left4 bbot4 wid2 height], ...
    'String',' ',...
    'BackgroundColor',color);

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot5 wid1 height], ...
    'String',' ',...
    'BackgroundColor',color);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hrhol = uicontrol('Style','text', ...
    'Position',[left4 bbot5 wid2 height], ...
    'String',' ',...
    'BackgroundColor',color);

ht  = uicontrol('Style','text', ...
    'Position',[left3 bbot6 wid1 height], ...
    'String',' ',...
    'BackgroundColor',color);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hnu = uicontrol('Style','text', ...
    'Position',[left4 bbot6 wid2 height], ...
    'String',' ',...
    'BackgroundColor',color);
end;    
