% INPUT_PARA1 reads SAMPLING_F (the sampling frequency), CHANNEL_X, CHANNEL_Y and CHANNEL_Z (positions of the X-, Y- and Z-
% data in the input file), WANT_DECORR (choice of using decorrelation of channels), and gives a VIEW_DATA button.

%xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
global prgVr sampling_f fNyq

n           =   0;              %number of aliasing terms to include, will be set later to a nonzero value
if prgVr.setupStt == 2
    sampling_f = calData.data(2).Property(6).Value/1000; % (kHz)  ---> change here if you want another default sampling frequency
elseif prgVr.setupStt == 1
    sampling_f  =   str2num(calData.textdata{2,1}{1}(strfind(calData.textdata{2,1}{1},':')+1:strfind(calData.textdata{2,1}{1},':')+4));             % (kHz)  ---> change here if you want another default sampling frequency
else    
    sampling_f  =   60;             % (kHz)  ---> change here if you want another default sampling frequency
end
fNyq        =   1000*sampling_f/2;   % Nyquist frequency. In Hz.
want_decorr =   0;              % want_decorr = 1 for decorrelation; otherwise 0

ht  = uicontrol('Style','text', ...
    'Position',[left1 bbot1 wid1 height], ...
    'String','Sampling frequency (kHz)',...
    'BackgroundColor',color1);
jh = findjobj(ht);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
hsampling_f = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[left2 bbot1 wid2 height], ...
    'String',num2str(sampling_f),...
    'BackgroundColor',color2,...
    'Callback','sampling_f = str2num(get(hsampling_f,''String'')); fNyq = 1000*sampling_f/2; input_para2;');
if prgVr.setupStt == 0 %% Old Tweezers    
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot2 wid1 height], ...
        'String','Channel X  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_x = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot2 wid2 height], ...
        'String',num2str(channel_x),...
        'BackgroundColor',color2,...
        'Callback','channel_x = str2num(get(hchannel_x,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot3 wid1 height], ...
        'String','Channel Y  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_y = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot3 wid2 height], ...
        'String',num2str(channel_y),...
        'BackgroundColor',color2,...
        'Callback','channel_y = str2num(get(hchannel_y,''String''));input_para1_dec;');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot4 wid1 height], ...
        'String','Channel Z  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_z = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot4 wid2 height], ...
        'String',num2str(channel_z),...
        'BackgroundColor',color2,...
        'Callback','channel_z = str2num(get(hchannel_z,''String''));');
elseif prgVr.setupStt == 1 %% Foldometer
%     ht  = uicontrol('Style','text', ...
%         'Position',[left1 bbot2 wid1 height], ...
%         'String','Channel X  =  column no.',...
%         'BackgroundColor',color1);
%     jh = findjobj(ht);
%     jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
%     hchannel_x = uicontrol('Style','edit', ...
%         'Units','normalized', ...
%         'Position',[left2 bbot2 wid2 height], ...
%         'String',num2str(channel_x),...
%         'BackgroundColor',color2,...
%         'Callback','channel_x = str2num(get(hchannel_x,''String''));');
%     ht  = uicontrol('Style','text', ...
%         'Position',[left1 bbot3 wid1 height], ...
%         'String','Channel Y  =  column no.',...
%         'BackgroundColor',color1);
%     jh = findjobj(ht);
%     jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
%     hchannel_y = uicontrol('Style','edit', ...
%         'Units','normalized', ...
%         'Position',[left2 bbot3 wid2 height], ...
%         'String',num2str(channel_y),...
%         'BackgroundColor',color2,...
%         'Callback','channel_y = str2num(get(hchannel_y,''String''));input_para1_dec;');
%     ht  = uicontrol('Style','text', ...
%         'Position',[left1 bbot4 wid1 height], ...
%         'String','Channel Z  =  column no.',...
%         'BackgroundColor',color1);
%     jh = findjobj(ht);
%     jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
%     hchannel_z = uicontrol('Style','edit', ...
%         'Units','normalized', ...
%         'Position',[left2 bbot4 wid2 height], ...
%         'String',num2str(channel_z),...
%         'BackgroundColor',color2,...
%         'Callback','channel_z = str2num(get(hchannel_z,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot2+0.3*height wid1 0.7*height], ...
        'String','Channel X-1  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_x_1 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot2+0.3*height wid2 0.7*height], ...
        'String',num2str(channel(1)),...
        'BackgroundColor',color2,...
        'Callback','channel(1) = str2num(get(hchannel_x_1,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot3+0.6*height wid1 0.7*height], ...
        'String','Channel Y-1  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_y_1 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot3+0.6*height wid2 0.7*height], ...
        'String',num2str(channel(2)),...
        'BackgroundColor',color2,...
        'Callback','channel(2) = str2num(get(hchannel_y_1,''String''));input_para1_dec;');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot4+0.9*height wid1 0.7*height], ...
        'String','Channel X-2  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_x_2 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot4+0.9*height wid2 0.7*height], ...
        'String',num2str(channel(3)),...
        'BackgroundColor',color2,...
        'Callback','channel(3) = str2num(get(hchannel_x_2,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot5+1.2*height wid1 0.7*height], ...
        'String','Channel Y-2  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_y_2 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot5+1.2*height wid2 0.7*height], ...
        'String',num2str(channel(4)),...
        'BackgroundColor',color2,...
        'Callback','channel(4) = str2num(get(hchannel_y_2,''String''));');
elseif prgVr.setupStt == 2 %% CTRAP
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot2+0.3*height wid1 0.7*height], ...
        'String','Channel X-1  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_x_1 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot2+0.3*height wid2 0.7*height], ...
        'String',num2str(channel(1)),...
        'BackgroundColor',color2,...
        'Callback','channel(1) = str2num(get(hchannel_x_1,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot3+0.6*height wid1 0.7*height], ...
        'String','Channel Y-1  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_y_1 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot3+0.6*height wid2 0.7*height], ...
        'String',num2str(channel(2)),...
        'BackgroundColor',color2,...
        'Callback','channel(2) = str2num(get(hchannel_y_1,''String''));input_para1_dec;');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot4+0.9*height wid1 0.7*height], ...
        'String','Channel X-2  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_x_2 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot4+0.9*height wid2 0.7*height], ...
        'String',num2str(channel(3)),...
        'BackgroundColor',color2,...
        'Callback','channel(3) = str2num(get(hchannel_x_2,''String''));');
    ht  = uicontrol('Style','text', ...
        'Position',[left1 bbot5+1.2*height wid1 0.7*height], ...
        'String','Channel Y-2  =  column no.',...
        'BackgroundColor',color1);
    jh = findjobj(ht);
    jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );
    hchannel_y_2 = uicontrol('Style','edit', ...
        'Units','normalized', ...
        'Position',[left2 bbot5+1.2*height wid2 0.7*height], ...
        'String',num2str(channel(4)),...
        'BackgroundColor',color2,...
        'Callback','channel(4) = str2num(get(hchannel_y_2,''String''));');
    
end
%channel_y = str2num(get(hchannel_y,'String'));
input_para1_dec;

hview_data  = uicontrol('Style','Pushbutton', ...
    'Position',[left1+wid1/2 bbot7 (wid1+wid2)/2 0.9*height], ...
    'String','View data',...
    'FontSize',titlefs+0.2,...
    'BackgroundColor',[1 0.1 0.1],...
    'Callback','view_data');
jh = findjobj(hview_data);
jh.setVerticalAlignment( javax.swing.AbstractButton.CENTER );