set(gcf,'DefaultUicontrolUnits','normalized','DefaultUicontrolFontUnits','normalized',...
    'DefaultUicontrolFontSize',0.6,'DefaultUicontrolFontWeight','bold')
try gcf;
    curFigTemp = gcf;
    if strncmp(curFigTemp.Name,'Distribution of X',17); NbinGaus = str2num(get(hNbinGausX{str2num(curFigTemp.Name(19))},'String')); 1; end;
    if strncmp(curFigTemp.Name,'Distribution of Y',17); NbinGaus = str2num(get(hNbinGausY{str2num(curFigTemp.Name(19))},'String')); 2; end;
catch; end;

if ~exist('NbinGaus'), NbinGaus = 50; end;
if ~exist('Tit'), Tit = ' '; end;
position_histogram_e(pos,NbinGaus,Tit);

ht  = uicontrol('Style','text', ...
    'Position',[0.3 0.03 0.28 0.03], ...
    'String','Number of bins',...
    'BackgroundColor',[0.6 0.7 0.4]);

if strncmp(curFigTemp.Name,'Distribution of X',17)
    hNbinGausX{str2num(curFigTemp.Name(19))} = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[0.6 0.03 0.1 0.03], ...
    'String',num2str(NbinGaus),...
    'BackgroundColor','w',...
    'Callback','curFigTemp = gcf; NbinGaus = str2num(get(hNbinGausX{str2num(curFigTemp.Name(19))},''String'')); clf; clear curFigTemp; plot_histogram;');
elseif strncmp(curFigTemp.Name,'Distribution of Y',17)
    hNbinGausY{str2num(curFigTemp.Name(19))} = uicontrol('Style','edit', ...
    'Units','normalized', ...
    'Position',[0.6 0.03 0.1 0.03], ...
    'String',num2str(NbinGaus),...
    'BackgroundColor','w',...
    'Callback','curFigTemp = gcf; NbinGaus = str2num(get(hNbinGausY{str2num(curFigTemp.Name(19))},''String'')); clf; clear curFigTemp; plot_histogram;');
end;

clear curFigTemp;